# Generated by Django 4.2.6 on 2023-11-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitem',
            name='archived',
        ),
    ]
