# Generated by Django 4.2.6 on 2023-11-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='rating',
        ),
    ]
