# Generated by Django 4.2.7 on 2023-11-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_delivery_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_driver',
        ),
    ]
